PAID_LABEL_TEXT = 'Paid'
UNPAID_LABEL_TEXT = 'Unpaid'
SHOPS = ["Jumbo", "Polish store"]
TO_BUY_LIST = "Buy"
BOUGHT_LIST = "Bought"

LABELS = [PAID_LABEL_TEXT, UNPAID_LABEL_TEXT] + SHOPS
LISTS = [BOUGHT_LIST, TO_BUY_LIST]
